[package]
name = "cowiki-desktop"
version = "0.1.0"
description = "CoWiki desktop client"
authors = ["CoWiki"]
edition = "2021"

[workspace]

[lib]
name = "cowiki_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
time = "=0.3.44"
